let alimentosJson = [
    {id:1, name:'Bawl de Comida Asiática', img:'images/comidaAsiatica.png', price:20.90, sizes:['200g', '400g', '550g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:3, name:'Salada de Folhas', img:'images/saladaDeFolhas.png', price:22.36, sizes:['Mini', 'Para 2', 'Família'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:2, name:'Bawl de Frutas com Chia', img:'images/BawlFrutasComChia.png', price:12.90, sizes:['100g', '250g', '300g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:4, name:'Salada Mista', img:'images/saladaMista.png', price:18.55, sizes:['320g', '530g', '860g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:5, name:'Spaghetti com Molho Vermelho', img:'images/spaghetti.png', price:18.55, sizes:['320g', '530g', '860g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:6, name:'Sopa com Proteína e Legumes', img:'images/sopa.png', price:18.55, sizes:['320g', '530g', '860g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:7, name:'Torrada com Frutas', img:'images/torradaComFrutas.png', price:22.36, sizes:['320g', '530g', '860g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:8, name:'Torta de Maçã', img:'images/tortaDeMaca.png', price:18.55, sizes:['320g', '530g', '860g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:9, name:'Sobremesa: Bolo de Frutas Vermelhas', img:'images/bolo.png', price:17.45, sizes:['320g', '530g', '860g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:10, name:'Bolinhos de Batata', img:'images/bolinhosDeBatata.png', price:19.77, sizes:['320g', '530g', '860g'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
    {id:11, name:'Porção Crocante', img:'images/porcaoCrocante.png', price:21.43, sizes:['Mini', 'Para 2', 'Família'], description:'Feito de forma caseira, com ingredientes frescos de primeira linha e no forno a lenha'},
];